from __future__ import annotations
import pandas as pd

LT_COLUMNS = [
    "long_term_rank",
    "long_term_rank_change_7d",
    "short_term_rank",
    "symbol",
    "company_name",
    "index_name",
    "sector",
    "long_term_score",
    "long_term_risk_adjusted_score",
    "quality_score",
    "growth_score",
    "valuation_score",
    "expectations_long_score",
    "long_trend_score",
    "risk_score",
    "risk_coverage",
    "fundamentals_basis",
    "expectations_direction",
    "overall_data_status",
    "confidence_score",
    "short_term_score",
    "current_price",
    "target_upside_pct",
    "eps_0q_change_30d_pct",
    "forward_eps_growth",
    "forward_revenue_growth",
    "lt_top_positive_driver",
    "lt_top_negative_driver",
]
ST_COLUMNS = [
    "short_term_rank",
    "short_term_rank_change_7d",
    "long_term_rank",
    "symbol",
    "company_name",
    "index_name",
    "short_term_score",
    "short_term_risk_adjusted_score",
    "short_term_setup",
    "long_term_score",
    "short_rs_score",
    "setup_quality_score",
    "expectations_short_score",
    "earnings_drift_score",
    "expectations_direction",
    "volume_confirmation_score",
    "technical_trend_score",
    "positioning_score",
    "event_timing_score",
    "risk_score",
    "risk_coverage",
    "market_regime",
    "rs_basis",
    "overall_data_status",
    "confidence_score",
    "current_price",
    "stop_loss_price",
    "target_price",
    "suggested_position_pct",
    "return_1d_pct",
    "return_5d_pct",
    "return_20d_pct",
    "drawdown_from_20d_high_pct",
    "days_to_next_earnings",
    "earnings_imminent_flag",
    "st_top_positive_driver",
    "st_top_negative_driver",
]
ACTION_COLUMNS = [
    "action_rank",
    "symbol",
    "company_name",
    "sector",
    "index_name",
    "short_term_setup",
    "short_term_rank",
    "long_term_rank",
    "short_term_risk_adjusted_score",
    "long_term_score",
    "current_price",
    "stop_loss_price",
    "stop_loss_pct",
    "target_price",
    "portfolio_weight_pct",
    "suggested_position_pct",
    "holding_period_sessions",
    "market_regime",
    "risk_score",
    "earnings_imminent_flag",
    "days_to_next_earnings",
    "st_top_positive_driver",
    "st_top_negative_driver",
]

INVESTMENT_RANKING_COLUMNS = [
    # Identity and independent horizon rankings.
    "symbol",
    "company_name",
    "index_name",
    "sector",
    "long_term_rank",
    "long_term_rank_change_7d",
    "long_term_score",
    "long_term_score_change_7d",
    "short_term_rank",
    "short_term_rank_change_7d",
    "short_term_score",
    "short_term_score_change_7d",
    "short_term_setup",
    "long_term_risk_adjusted_score",
    "short_term_risk_adjusted_score",
    # Risk, confidence and the short-term trade plan.
    "risk_score",
    "confidence_score",
    "market_regime",
    "stop_loss_price",
    "target_price",
    "suggested_position_pct",
    # Existing analyst point-in-time history.
    "target_mean",
    "target_mean_change_7d_pct",
    "target_mean_change_30d_pct",
    "target_mean_change_90d_pct",
    "target_median",
    "target_median_change_7d_pct",
    "target_median_change_30d_pct",
    "target_median_change_90d_pct",
    "revenue_0q_change_7d_pct",
    "revenue_0q_change_30d_pct",
    "revenue_0q_change_90d_pct",
    "revenue_plus_1q_change_7d_pct",
    "revenue_plus_1q_change_30d_pct",
    "revenue_plus_1q_change_90d_pct",
    "revenue_0y_change_30d_pct",
    "revenue_0y_change_90d_pct",
    "revenue_plus_1y_change_30d_pct",
    "revenue_plus_1y_change_90d_pct",
    # Long-term and short-term model components remain separate.
    "quality_score",
    "growth_score",
    "valuation_score",
    "expectations_long_score",
    "long_trend_score",
    "financial_safety_score",
    "short_rs_score",
    "setup_quality_score",
    "expectations_short_score",
    "earnings_drift_score",
    "volume_confirmation_score",
    "technical_trend_score",
    "positioning_score",
    "event_timing_score",
    # Current market context.
    "current_price",
    "return_20d_pct",
    "return_60d_pct",
    "return_126d_pct",
    "distance_to_52w_high_pct",
    # Compact data and history status.
    "overall_data_status",
    "price_data_status",
    "analyst_cache_status",
    "valuation_cache_status",
    "fundamental_cache_status",
    "targets_cache_status",
    "revenue_estimate_cache_status",
    "rank_history_status",
    "long_term_score_history_status",
    "short_term_score_history_status",
    "long_term_rank_history_status",
    "short_term_rank_history_status",
]


def _show(frame, columns, top):
    cols = [c for c in columns if c in frame]
    display = frame[cols].head(top).copy()
    return display.to_string(
        index=False, max_colwidth=38, float_format=lambda x: f"{x:.1f}"
    )


def print_rankings(
    lt: pd.DataFrame, st: pd.DataFrame, top: int, action: pd.DataFrame | None = None
):
    print("\nLONG-TERM INVESTMENT RANKING\n")
    print(_show(lt, LT_COLUMNS, top))
    print("\nSHORT-TERM OPPORTUNITY RANKING\n")
    print(_show(st, ST_COLUMNS, top))
    if action is not None and len(action):
        print("\nACTION LIST (short-term timing inside the long-term top half)\n")
        print(_show(action, ACTION_COLUMNS, len(action)))
